# Generated by Django 5.0.6 on 2024-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(upload_to='logos/'),
        ),
    ]
