# Generated by Django 5.0.6 on 2024-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='practice_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.FileField(help_text='Image dimensions should be 250px (width) by 75px (height).', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='Image dimensions should be 1500px (width) by 800px (height).', upload_to='slider/'),
        ),
    ]
