# Generated by Django 5.0.6 on 2024-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
